image: ruby:2.2.3
git:
  path: github.com/dtan4/ramesh-dashboard
env:
  - RAILS_ENV=test
services:
  - postgres
script:
  - bundle install -j4
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake spec
