image: ruby:2.2.3
cache:
  - vendor/bundle
env:
  - RAILS_ENV=test
services:
  - postgresql
script:
  - bundle install -j4 --path=vendor/bundle
  - bundle exec rake db:test:prepare
  - bundle exec rspec
