image: ruby:2.2.3
git:
  path: github.com/dtan4/ramesh-dashboard
  depth: 1
cache:
  - vendor/bundle
env:
  - RAILS_ENV=test
services:
  - postgres
script:
  - bundle install -j4 --path=vendor/bundle
  - bundle exec rake db:test:prepare
  - bundle exec rspec
