image: ruby:2.2.3
git:
  path: github.com/dtan4/ramesh-dashboard
services:
  - postgres
env:
  - RAILS_ENV=test
script:
  - bundle install -j4
  - bundle exec rake db:schema:load
  - bundle exec rake spec
