# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c17f280fcc694707f0c6e22f07e901817360411c75bb98a16d48304e181c4439184900b8a6df8680d68bd99307de0ab3db661b1ca77f39d1130619b3760bc2f

test:
  secret_key_base: ec2dc7c8d0b715cc86912163a12c1ca47ec446750c8f4f78a8c23549450d2f566e25d5fe5c37ff5c704b78b7442af0d0f517855979f0ff5c237f13b8cfe9777a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
